soal_umum = [
    {"soal": "Apa nama ibukota Prancis?", "jawaban": "paris"},
    {"soal": "Apa nama sungai terpannjang di dunia?", "jawaban": "nil"},
    {"soal": "Nama resmi negara Belanda adalah", "jawaban": "netherland"},
    {"soal": "Mata uang negara jepang adalah", "jawaban": "yen"},
    {"soal": "Layar komputer disebut juga", "jawaban": "monitor"},
    {"soal": "Arah jam 9 itu sama dengan arah", "jawaban": "barat"},
    {"soal": "Patung Sphinx kebanyakan terdapat di negara", "jawaban": "mesir"},
    {"soal": "Gunung kilimanjaro terletak di negara?", "jawaban": "tanzania"},
    {"soal": "Dimanakah letak menara Pisa", "jawaban": "italia"},
    {"soal": "Covid 19 pertama kali muncul di kota", "jawaban": "wuhan"},
    {"soal": "Hewan paling cerdas di dunia adalah", "jawaban": "simpanse"},
    {"soal": "Negara terluas di dunia adalah", "jawaban": "rusia"},
    {"soal": "Gurun terluas di dunia adalah", "jawaban": "sahara"},
    {"soal": "Tahun yang ada tanggal 29 februari disebut tahun?", "jawaban": "kabisat"},
    {"soal": "Puan maharani berasal dari partai", "jawaban": "pdip"}
]

soal_ipa = [
    {"soal": "Alat ukur tekanan udara adalah",
     "jawaban": "barometer"},
    {"soal": "Simbol kimia perak adalah", "jawaban": "ag"},
    {"soal": "Apa nama planet terdekat dari matahari?",
     "jawaban": "merkurius"},
    {"soal": "Simbol kimia emas adalah",
     "jawaban": "au"},
    {"soal": "Apa komponen utama dalam atmosfer bumi?",
     "jawaban": "nitrogen"},
    {"soal": "Alat ukur suhu tubuh adalah", "jawaban":
     "termometer"},
    {"soal": "Binatang yang hidup di dua alam disebut",
     "jawaban": "amfibi"},
    {"soal": "Pusat peredaran tata surya adalah",
     "jawaban": "matahari"},
    {"soal": "Hewan terkecil adalah",
     "jawaban": "amuba"},
    {"soal": "Ikan bernafas dengan",
     "jawaban": "insang"},
    {"soal": "Indra manusia yang digunakan untuk mengecap",
     "jawaban": "lidah"},
    {"soal": "Bahan yang digunakan lebah untuk membuat madu",
     "jawaban": "nektar"},
    {"soal": "Udara yang bergerak disebut",
     "jawaban": "angin"},
    {"soal": "Embrio manusia mendapatkan nutrisi melalui",
        "jawaban": "plasenta"},
    {"soal": "Hewan yang beraktifitas di malam hari disebut",
        "jawaban": "nokturnal"},
    {"soal": "Mamalia terbesar di dunia adalah",
     "jawaban": "paus"},
]

soal_pkn = [
    {"soal": "Berapakah jumlah bulu leher burung garuda", "jawaban": "45"},
    {"soal": "Bersatu kita teguh, bercerai kita", "jawaban": "runtuh"},
    {"soal": "Dasar negara indonesia adalah", "jawaban": "pancasila"},
    {"soal": "Apa ibukota papua?", "jawaban": "jayapura"},
    {"soal": "Bapak pendidikan nasional adalah", "jawaban": "ki hajar dewantara"},
    {"soal": "Bentuk negara indonesia adalah", "jawaban": "republik"},
    {"soal": "Lambang negara indonesia", "jawaban": "garuda"},
    {"soal": "Sumpah yang diucapkan patih gajah mada disebut",
        "jawaban": "palapa"},
    {"soal": "Siapa raja pertama kerajaan kutai", "jawaban": "kudungga"},
    {"soal": "Apa nama kerajaan yang didirikan Ken Arok", "jawaban": "singasari"},
    {"soal": "Siapa presiden kedua Indonesia?", "jawaban": "soeharto"},
    {"soal": "Kapan Indonesia merdeka?", "jawaban": "17 agustus 1945"},
    {"soal": "Sebutkan sila ketiga pancasila", "jawaban": "persatuan indonesia"},
    {"soal": "Tahun berapa agresi militer belanda 2",
        "jawaban": "1948"},
    {"soal": "Kapan hari pendidikan nasional diperingati", "jawaban": "2 mei"},
]
